import '@angular/common';
import '@angular/core';
// angular
import '@angular/platform-browser';
import '@angular/platform-browser-dynamic';
import 'core-js/es6';
import 'core-js/es7/reflect';
// RxJS
import 'rxjs/Rx';
import 'zone.js/dist/zone';